### ISSUE TITLE
カレンダーの日付ブロック内の部分に[昼][夜]ボタン設置

### ISSUE THREAD

**Issue by masato-n** [TeijigoTeaTime/meshido-desktop#8]
### 機能の概要

カレンダーの日付ブロック内の部分に[昼][夜]ボタン設置する
### 要件（＝このIssueでやること）
- 日付ブロック内にボタンを設置
  - [昼]ボタン
  - [夜]ボタン
- 投下されたボタンは色を変更する
### スコープ外の要件（＝このIssueではやらないこと）
- サーバへのデータ送受信
- 登録人数の表示
## その他備考
- ボタンは画像に差し替える可能性あり

**Comment by kawanamiyuu** [comment]
@masato-n: 
- ランチのボタン、人数の親要素には、idとして ~~`msd-event-年-月-日`~~ **`msd-lunch-年-月-日`** 、classとして `msd-js-event` を、 ランチボタンにはclassとして ~~`msd-js-join-lunch`~~ **`msd-js-join-event`** を、ランチ人数にはclassとして `msd-js-event-people`をセットしてください。
- 同様に、ディナーのボタン、人数の親要素には、idとして ~~`msd-event-年-月-日`~~ **`msd-dinner-年-月-日`**  、classとして `msd-js-event` をを、 ディナーボタンにはclassとして ~~`msd-js-join-dinner`~~  **`msd-js-join-event`** を、ディナー人数にはclassとして `msd-js-event-people`をセットしてください。

（例）2015/12/16 のランチ

``` html
<div id=“msd-lunch-2015-12-16” class="msd-js-event">
    <button class=“msd-js-join-event">昼</button>
   <div class="msd-js-event-people">5</div>
</div>
```

ボタンを押した時にJavascriptで、年月日や、ランチなのかディナーなのかを特定するためです。
使用するタグや要素の階層は特に指定はありません。お任せします。

---

※ `msd-`はこのアプリ固有のidとclassとひと目で分かるために付けるPrefixとします。
※ `msd-js-`はJavascriptから操作するためのclassのPrefixとします。

**Comment by kawanamiyuu** [comment]
@masato-n ↓の仕様を実装してください。
- イベントに参加状態(`hasJoined`)の場合、 **`msd-js-event`クラスを持つ要素** に、`msd-js-event-joined`クラス（JS用） **と`msd-event-joined`クラス（デザイン用）** を付与する
- イベントが確定済み(`isFixed`)の場合、 **`msd-js-event`クラスを持つ要素** に、`msd-js-event-fixed`クラス（JS用） **と`msd-event-fixed`クラス（デザイン用）** を付与する

例）参加状態、かつ、確定済みの場合

``` html
<div id=“msd-lunch-2015-12-16” 
    class="msd-js-event 
           msd-js-event-joined msd-js-event-fixed 
           msd-event-joined msd-event-fixed">

    <button class=“msd-js-join-event">昼</button>
    <div class="msd-js-event-people">5</div>
</div>
```

**Comment by kawanamiyuu** [comment]
@masato-n ちなみに、`msd-js-`プレフィックスが付いているclassにはスタイルを定義しないように注意してください。スタイルは別のclass(`msd-`プレフィックス付き)で定義してください。

例

``` css
.msd-event-joined .msd-join-btn {
  background-color: lightgrey;
}
```

``` html
<div id=“...” class="... msd-js-event-joined msd-event-joined">
    <button class=“... msd-join-btn">昼</button>
    <div class="...">5</div>
</div>
```

理由は、Javascript用のclassと、デザイン用のclassを分けることで、ロジックと表示(View)を疎結合にするためです。

※デザイン用のclass名は上の例のように別に`msd-js-`の`js-`を取ったものである必要はありません。適切なclass名をつけてください。（ただし、`msd-`プレフィックスは必須）
